quarkus:
  devservices:
    enabled: false
  http:
    port: 8666
  langchain4j:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat-model:
        model-name: gpt-4
        temperature: 0.7
    log-requests: true
    log-responses: true

